mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('polls.urls', 'polls')),
    path('admin/', admin.site.urls),

]

mysite/polls/urls.py
from django.urls import path

from .views import index
from .views import openpage
from .views import BBLogoutView, RegisterDoneView
from .views import login
from .views import register


app_name = 'main'
urlpatterns = [
    path('', index, name='index'),
    path('<str:page>/', openpage, name='other'),
    path('account/logout/', BBLogoutView.as_view(), name='logout'),
    path('login/', login, name='login'),  # Имя URL для входа
    path('register/', register, name='register'),
    path('account/register/done/', RegisterDoneView.as_view(), name='register_done'),
]

mysite/polls/models.py
from django.contrib.auth.models import AbstractUser


class AdvUser(AbstractUser):
    class Meta(AbstractUser.Meta):
        pass

def user_registrated():
    return None

mysite/polls/forms.py
# main/forms.py
from django import forms
from django.contrib.auth.models import User

class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password_confirm = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']  # Убедитесь, что перечислены все необходимые поля

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_confirm = cleaned_data.get("password_confirm")

        if password != password_confirm:
            raise forms.ValidationError("Пароли не совпадают.")
        return cleaned_data

class AuthenticationForm(forms.Form):
    username = forms.CharField(label='Логин', max_length=150)
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)

mysite/polls/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.http import Http404
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.contrib.auth.views import TemplateView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin

from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login as auth_login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import RegisterForm

def index(request):
    return render(request, 'main/index.html')

class RegisterDoneView(TemplateView):
    template_name = 'main/register_done.html'

def openpage(request, page):
    try:
        template = get_template(f'main/{page}.html')  # Исправлено: добавлено '/'
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)

            if user is not None:
                auth_login(request, user)
                messages.success(request, "Вы вошли в систему!")
                return redirect('main:home')  # Перенаправление после успешного входа
            else:
                messages.error(request, "Неверные учетные данные.")
    else:
        form = AuthenticationForm()

    return render(request, 'login.html', {'form': form})

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])  # Убедитесь, что сохраняете хэш пароля
            user.save()
            messages.success(request, "Вы успешно зарегистрировались!")
            return redirect('main:login')  # или на страницу входа
    else:
        form = RegisterForm()  # Создание пустой формы

    return render(request, 'register.html', {'form': form})



class BBLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'main/logout.html'

mysite/polls/templates/main/index.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="../static/main/style.css">
    <title>{% block title %} Главная {% endblock %}</title>
</head>
<body>
<div class="container-fluid">
    <div class="">
        <div class="nav-item dropdown">
            <div class="dropdown_header">
                {% if user.is_authenticated %}
                <p>Привет, {{ user.username }}! <a href="{% url 'main:logout' %}">Выйти</a></p>
                {% else %}
                <div class="nav_dropdown_header">
                    <a class="nav-link" href="{% url 'main:login' %}">Вход</a>
                    <a class="nav-link" href="{% url 'main:register' %}">Регистрация</a>
                    {% if messages %}
                    {% for message in messages %}
                    <div class="alert alert-success">{{ message }}</div>
                    {% endfor %}
                    {% endif %}
                {% endif %}
                </div>
            </div>
            <div class="dropdown_menu_head">
                <h2>meow</h2>
                {% block content %}

                {% endblock %}
            </div>
        </div>

    </div>
</div>

    <footer class="mt-3 border-top"></footer>
</body>
<style>
*{
    max-width: 100%
    margin: 0 auto;
}
body{
    display: flex;
    margin-left: 50px;
    width: 100%;
    margin-right: 50px;
}

.dropdown_header {
    padding-top: 1%;
    margin-left: 70%;
}

.nav_dropdown_header{
    display: flex;
    align-items: center;
    justify-content: space-between;
    flex-direction: row;
    gap: 50px;
}

.nav_dropdown_header{
    margin-left: 37%;
}

.row {
    margin-top: 5%;
}

.dropdown_header{
    display: flex;

}
.container-fluid{
    width: 100vw;
    margin: 0 auto;
    margin-top: 20px;
    margin-left: 30px;
    margin-right: 30px;
}
.dropdown-toggle{
    margin-left: 70%;
}

.text-dark{
   margin-left: 5%;
}

.nav_dropdown_header a {
    color: black;
    background-color: #d7e7ff;
    text-decoration: none;
    border-radius: 10px;
    padding: 5% 7% 5% 7%;
}

.nav_dropdown_header a:hover{
    color: black;
    background-color: #b9d6ff;
    text-decoration: none;
    border-radius: 10px;
    padding: 5% 7% 5% 7%;
}
</style>
</html>

mysite/polls/templates/main/login.html
{% extends 'main/index.html' %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Вход</title>
</head>
<body>
    <h2>Вход в систему</h2>

    {% if messages %}
        {% for message in messages %}
            <div class="alert">{{ message }}</div>
        {% endfor %}
    {% endif %}

    <form method="POST">
        {% csrf_token %}
        {{ form.username.label }}<br>
        {{ form.username }}<br>
        {{ form.password.label }}<br>
        {{ form.password }}<br>
        <button type="submit">Войти</button>
    </form>
</body>
</html>

mysite/polls/templates/main/logout.html
{% extends "main/index.html" %}

{% block title %} Выход {% endblock %}
{% block content %}
    <h2>Выход</h2>
    <p>Вы успешно вышли с сайта.</p>
{% endblock %}

mysite/polls/templates/main/register.html
{% extends 'main/index.html' %}

{% block content %}
  <h2>Регистрация</h2>

  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }}">
        {{ message }}
      </div>
    {% endfor %}
  {% endif %}

  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}  <!-- Это должно корректно отображать форму -->
    <button type="submit">Зарегистрироваться</button>
  </form>
{% endblock %}

mysite/polls/templates/main/register_done.html
{% extends "main/index.html" %}


{% block title %} Регистрация завершена {% endblock %}

{% block content %}
    <h2>Регистрация</h2>
    <p>Регистрация пользователя завершена</p>
    <p>На адрес электронной почты, указанный пользователем, выслано письмо для активации</p>
{% endblock %}

mysite/polls/templates/main/welcome_message.html
{% extends 'main/index.html' %}

{% block title %}Главная страница{% endblock %}